[package]
name = "tscred"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = "0.2.15"
reqwest = { version = "0.12.24", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
url = "2.5.7"
