[package]
name = "freebie"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
jiff.workspace = true
tscred = { version = "0.1.0", path = "../tscred" }
umya-spreadsheet = "2.3.3"

[dev-dependencies]
serde_json = "1.0.145"
