name: CI/CD
on:
  push:
  pull_request:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with: &cache-inputs
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: taisugar-toolkit
          path: target/release/taisugar_toolkit.exe

  test:
    name: Test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
      - name: Cache
        uses: actions/cache@v4
        with: *cache-inputs
      - name: Run tests
        run: cargo test

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [ build, test ]

    permissions:
      contents: write

    env:
      RELEASE_ASSET: 台糖工具包-${{ github.event.release.name }}-windows-x64.exe

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: taisugar-toolkit
          path: target/release
      - name: Rename release assets
        run: mv target/release/taisugar_toolkit.exe target/release/${{ env.RELEASE_ASSET }}
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/${{ env.RELEASE_ASSET }}
